version: "3.9"

services:
  migrate:
    image: "migrate/migrate"
    networks:
      - tender-net
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:123321@postgres:5432/tender_management?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=tender_management
    networks:
      - tender-net
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - tender-net
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  auth:
    container_name: tender
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tender-net
    ports:
      - "8888:8888"

networks:
  tender-net:
    name: tender-net
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  migrations:
