definitions:
  entity.AwardedRes:
    properties:
      bide_id:
        type: string
      contractor_id:
        type: string
      tender_id:
        type: string
    type: object
  entity.Bid:
    properties:
      comments:
        type: string
      contractor_id:
        type: string
      delivery_time:
        description: in days
        type: integer
      id:
        type: string
      price:
        type: number
      status:
        description: e.g., 'pending'
        type: string
      tender_id:
        type: string
    type: object
  entity.Bid1:
    properties:
      comments:
        type: string
      delivery_time:
        description: in days
        type: integer
      price:
        type: number
      status:
        description: e.g., 'pending'
        type: string
    type: object
  entity.Error:
    properties:
      error:
        type: string
    type: object
  entity.LogInReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  entity.LogInRes:
    properties:
      expire_at:
        type: integer
      token:
        type: string
      user_id:
        type: string
    type: object
  entity.Message:
    properties:
      message:
        type: string
    type: object
  entity.RegisterReq:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  entity.Tender:
    properties:
      budget:
        type: number
      client_id:
        type: string
      deadline:
        type: string
      description:
        type: string
      id:
        type: string
      status:
        type: string
      title:
        type: string
    type: object
  entity.TenderReq1:
    properties:
      budget:
        type: number
      deadline:
        type: string
      description:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
  description: Admin Panel for managing the CRM
  title: CRM API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login for admin users
      parameters:
      - description: Admin login
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/entity.LogInReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.LogInRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Error'
      summary: Admin Login
      tags:
      - User
  /auth/user/register:
    post:
      consumes:
      - application/json
      description: Register a new user account
      parameters:
      - description: Create user
        in: body
        name: CreateUser
        required: true
        schema:
          $ref: '#/definitions/entity.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.LogInRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Error'
      summary: Create User
      tags:
      - User
  /tenders:
    get:
      consumes:
      - application/json
      description: List all tenders for a specific client
      parameters:
      - description: Client ID to filter tenders
        in: query
        name: client_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Tender'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Error'
      summary: List All Tenders
      tags:
      - Tender
    post:
      consumes:
      - application/json
      description: Create a new tender for a client with details like title, description,
        deadline, and budget.
      parameters:
      - description: Create tender
        in: body
        name: CreateTender
        required: true
        schema:
          $ref: '#/definitions/entity.TenderReq1'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.Tender'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Error'
      summary: Create Tender
      tags:
      - Tender
  /tenders/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a tender by its ID
      parameters:
      - description: Tender ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Error'
      summary: Delete Tender
      tags:
      - Tender
  /tenders/{id}/{status}:
    put:
      consumes:
      - application/json
      description: Update the status of a tender (open, closed, awarded)
      parameters:
      - description: Tender ID
        in: path
        name: id
        required: true
        type: string
      - description: Update status
        in: path
        name: status
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Error'
      summary: Update Tender Status
      tags:
      - Tender
  /tenders/{id}/award/{bid_id}:
    post:
      consumes:
      - application/json
      description: Award a bid to a specific tender by tender ID and bid ID.
      parameters:
      - description: Tender ID
        in: path
        name: id
        required: true
        type: string
      - description: Bid ID
        in: path
        name: bid_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.AwardedRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Error'
      summary: Award Tender
      tags:
      - Tender
  /tenders/{id}/bids:
    get:
      consumes:
      - application/json
      description: Get a list of bids for a tender with optional filters for price,
        delivery time, and comments or status.
      parameters:
      - description: Tender ID
        in: path
        name: id
        required: true
        type: string
      - description: Filter by price
        in: query
        name: price
        type: number
      - description: Filter by delivery time
        in: query
        name: delivery_time
        type: integer
      - description: Filter by comments
        in: query
        name: comments
        type: string
      - description: Filter by status
        in: query
        name: status
        type: string
      - description: Client ID to filter tenders
        in: query
        name: client_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Bid'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Error'
      summary: Get Bids for Tender
      tags:
      - Bids
    post:
      consumes:
      - application/json
      description: Contractors can submit bids on open tenders
      parameters:
      - description: Tender ID
        in: path
        name: id
        required: true
        type: string
      - description: Bid details
        in: body
        name: bid
        required: true
        schema:
          $ref: '#/definitions/entity.Bid1'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.Bid'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Error'
      summary: Submit a bid on a tender
      tags:
      - Bids
  /users/{id}/bids:
    get:
      consumes:
      - application/json
      description: Retrieve all bids placed by a specific user.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Bid'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Error'
      summary: Get User Bids
      tags:
      - User
  /users/{id}/tenders:
    get:
      consumes:
      - application/json
      description: Get all tenders associated with a specific user.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Tender'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Error'
      summary: Get User Tenders
      tags:
      - User
securityDefinitions:
  BearerAuth:
    description: Enter your bearer token here
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
